Repository FaceTheFacts/web, pull requests merged in 2021-03, with the labels that each got.

#43 [Feature] Tabbar
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  CONTRIBUTING.md
  src/App.tsx
  src/Types.tsx
  src/amthor.tsx
  src/components/ElectionChancesCard.css
  src/components/ElectionChancesCard.tsx
  src/components/SearchResults.tsx
  src/components/StateListCard.tsx
  src/components/Tabs.css
  src/components/Tabs.tsx
  src/pages/ElectionChances.css
  src/pages/ElectionChances.tsx
Labels: enhancement

#44 [Feature] Profile: Segmentbuttons
  src/App.tsx
  src/components/CameraView/CameraFeed.test.tsx
  src/components/SegmentButtons.css
  src/components/SegmentButtons.tsx
  src/components/Tabs.css
  src/components/Tabs.tsx
  src/components/WahlchancenCard.tsx
  src/pages/Wahlchancen.tsx
Labels: enhancement

#50 [Feature] Profile: Header
  package-lock.json
  src/components/CameraView.tsx
  src/components/PoliticianProfile.css
  src/components/PoliticianProfile.tsx
Labels: enhancement

#53 [Design] Profile: redesign
  pytest/README.md
  src/components/ArrowLinkButton.css
  src/components/ArrowLinkButton.tsx
  src/components/CameraView.test.tsx
  src/components/CameraView.tsx
  src/components/CameraView/CameraFeed.tsx
  src/components/CameraView/DetectionCanvas.test.tsx
  src/components/CameraView/FeedbackCanvas.test.tsx
  src/components/PoliticianProfile.css
  src/components/PoliticianProfile.tsx
  src/components/SegmentButtons.tsx
  src/components/SideJobCard.css
  src/components/SideJobCard.tsx
  src/components/Tabs.css
  src/components/Tabs.tsx
  src/components/TopicCard.css
  src/components/TopicCard.test.tsx
  src/components/TopicCard.tsx
  src/components/VoteCard.css
  src/components/VoteCard.tsx
  src/components/VoteChart.css
  src/components/VoteChart.tsx
  src/pages/Discover.test.tsx
  src/pages/ElectionChances.tsx
  src/pages/Profile.css
  src/pages/Profile.test.tsx
  src/pages/Profile.tsx
  src/pages/Votes.test.tsx
  src/pages/__snapshots__/Discover.test.tsx.snap
Labels: design, enhancement

#56 [Hotfix] Discover: Test
  src/pages/Discover.test.tsx
  src/pages/__snapshots__/Discover.test.tsx.snap
Labels: bug

#68 Delete io-fix attribute and update Discover-Snaphot test
  package-lock.json
  src/pages/__snapshots__/Discover.test.tsx.snap
Labels: bug
